import streamlit as st
from report_analysis.pdf_reader import extract_text_from_pdf
from report_analysis.analyzer import analyze_report

# -------------------------------------------------
# Page Config
# -------------------------------------------------

st.set_page_config(
    page_title="Medical Report Analysis",
    page_icon="📄",
    layout="wide"
)

# -------------------------------------------------
# CSS
# -------------------------------------------------

st.markdown("""
<style>

.block-container{
    padding-top:2rem;
}

.title{
    font-size:45px;
    font-weight:bold;
    color:white;
    text-align:center;
}

.subtitle{
    text-align:center;
    color:#9ca3af;
    font-size:18px;
    margin-bottom:30px;
}

.card{
    background:#1B1F2A;
    border-radius:18px;
    padding:20px;
    border:1px solid #313543;
    transition:.3s;
}

.card:hover{
    border:1px solid #6C63FF;
}

.stButton>button{
    width:100%;
    height:48px;
    border-radius:14px;
    font-weight:bold;
}

.success-card{
    background:#18242E;
    padding:18px;
    border-radius:14px;
    border-left:5px solid #22C55E;
}

.info-card{
    background:#171B25;
    padding:18px;
    border-radius:14px;
    border-left:5px solid #6366F1;
}

</style>
""", unsafe_allow_html=True)

# -------------------------------------------------
# Header
# -------------------------------------------------

st.markdown(
'<div class="title">📄 Medical Report Analysis</div>',
unsafe_allow_html=True
)

st.markdown(
'<div class="subtitle">Upload your medical report and let MediAssist AI explain it in simple language.</div>',
unsafe_allow_html=True
)

# -------------------------------------------------
# Info Cards
# -------------------------------------------------

c1,c2,c3=st.columns(3)

with c1:

    st.markdown("""
<div class="card">

### 📤 Upload

Blood Reports

CBC

LFT

KFT

Urine Reports

</div>
""",unsafe_allow_html=True)

with c2:

    st.markdown("""
<div class="card">

### 🤖 AI Analysis

Easy Explanation

Summary

Abnormal Findings

Recommendations

</div>
""",unsafe_allow_html=True)

with c3:

    st.markdown("""
<div class="card">

### ⚡ Powered By

Groq Llama 3.3

RAG

Medical Knowledge Base

</div>
""",unsafe_allow_html=True)

st.write("")
st.markdown("---")

# -------------------------------------------------
# Upload Section
# -------------------------------------------------

uploaded_file = st.file_uploader(

    "📄 Upload Medical Report",

    type=["pdf"]

)

# -------------------------------------------------
# Upload Successful
# -------------------------------------------------

if uploaded_file:

    left,right = st.columns([3,1])

    with left:

        st.markdown("""
<div class="success-card">

### ✅ Report Uploaded Successfully

Your report is ready for AI analysis.

Click **Analyze Report** to continue.

</div>
""",unsafe_allow_html=True)

    with right:

        st.metric(
            "Pages",
            "PDF"
        )

    st.write("")

    # -----------------------------------------

    extracted_text = extract_text_from_pdf(uploaded_file)

    # -----------------------------------------

    with st.expander("📄 View Extracted Report"):

        st.text_area(

            "Report",

            extracted_text,

            height=320

        )

    st.write("")

    # -----------------------------------------

    if st.button("🧠 Analyze Report"):

        with st.spinner("Analyzing your report..."):

            result = analyze_report(extracted_text)

        st.success("Analysis Completed Successfully")

        st.write("")

        st.markdown("## 📝 AI Report Analysis")

        st.markdown(result)

        st.write("")

        st.markdown("---")

        st.info("""
⚠️ **Medical Disclaimer**

This analysis is generated by AI for educational purposes only.

Always consult a qualified healthcare professional before making any medical decisions.
""")